name: Workflow of exercise 6
run-name: Sixth workflow 
permissions:
    contents: read

# Events triggering the workflow
on: 
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    container-job:
        runs-on: ubuntu-latest
        container: pandoc/extra
        steps:
            - name: "Create file"
              run: pandoc --template eisvogel exercises.md -o exercises_v2.pdf
            - name: "Upload file"
              uses: actions/upload-artifact@v7
              with:
                name: my-artifact
                path: exercises_v2.pdf
                retention-days: 5 
