name: Workflow of exercise 3
run-name: Third workflow

# Events triggering the workflow
on:
    push:
        branches: [main]
    pull_request:
        branches:
            - main
    workflow_dispatch:

env:
    MyVariable: "Hello World"
    SecretValue: ${{ secrets.MySecret }}

jobs:
    job_id:
        runs-on: ubuntu-latest
        env:
            JobVariable: "This is a job variable"
        steps:
        - run: echo "${{env.MyVariable}}"
        - run: echo "${MyVariable}"
        - run: echo "${JobVariable}"
        - run: echo "${{secrets.GITHUB_TOKEN}}"
        - run: echo "${{github.token}}"
        - if: ${{env.SecretValue == 'jabberwocky'}}
          run: echo "secret is correct"

